import {
  Incident,
  MissingPerson,
  Sighting,
  HelpDesk,
  Volunteer,
  PolicePost,
  CCTVCamera,
  CrowdZone,
  ExitGate,
  VehicleTrip,
  NotificationItem,
  AuditLogEntry,
} from '@/types';

export const INITIAL_HELP_DESKS: HelpDesk[] = [
  {
    id: 'Desk-3',
    name: 'Help Desk 3 (Zone B - Central Pathway)',
    location: 'Zone B - Main Pathway Kiosk',
    coords: [21.12785, 79.06690],
    operatorsCount: 4,
    activeCasesCount: 5,
    capacity: 15,
    status: 'ACTIVE',
    phone: '+91 712 256 0103',
    leadOperator: 'Ramesh Kamble',
    zone: 'Zone B',
  },
  {
    id: 'HD-01',
    name: 'Help Desk 1 (Zone A - North Gate)',
    location: 'Zone A - North Gate 1 VIP Road',
    coords: [21.12930, 79.06690],
    operatorsCount: 3,
    activeCasesCount: 4,
    capacity: 15,
    status: 'ACTIVE',
    phone: '+91 712 256 0101',
    leadOperator: 'Sunil Meshram',
    zone: 'Zone A',
  },
  {
    id: 'HD-02',
    name: 'Help Desk 2 (Zone A - Food Court)',
    location: 'Zone A - Food Court & Annadanam',
    coords: [21.12870, 79.06820],
    operatorsCount: 4,
    activeCasesCount: 6,
    capacity: 18,
    status: 'ACTIVE',
    phone: '+91 712 256 0102',
    leadOperator: 'Priyanka Patil',
    zone: 'Zone A',
  },
  {
    id: 'HD-04',
    name: 'Help Desk 4 (Zone C - Parking & Transit)',
    location: 'Zone C - South Concourse',
    coords: [21.12620, 79.06690],
    operatorsCount: 5,
    activeCasesCount: 11,
    capacity: 20,
    status: 'OVERLOADED',
    phone: '+91 712 256 0104',
    leadOperator: 'Anjali Moon',
    zone: 'Zone C',
  },
  {
    id: 'HD-05',
    name: 'Help Desk 5 (Zone D - Backside Path)',
    location: 'Zone D - West Perimeter',
    coords: [21.12785, 79.06450],
    operatorsCount: 3,
    activeCasesCount: 3,
    capacity: 12,
    status: 'ACTIVE',
    phone: '+91 712 256 0105',
    leadOperator: 'Dr. Rahul Wankhede',
    zone: 'Zone D',
  },
];

export const INITIAL_POLICE_POSTS: PolicePost[] = [
  {
    id: 'PP-01',
    name: 'Nearby Police Post (Zone B - 420m)',
    location: 'Zone B Main Junction Post',
    coords: [21.12810, 79.06620],
    officersCount: 18,
    vehicleUnits: 3,
    contact: '+91 712 256 1001',
    activeResponses: 2,
    inCharge: 'Inspector Abhay Dongre',
    status: 'ACTIVE',
  },
  {
    id: 'PP-02',
    name: 'Police Post 2 (Zone A Security)',
    location: 'Zone A Food Court Patrol',
    coords: [21.12890, 79.06690],
    officersCount: 14,
    vehicleUnits: 2,
    contact: '+91 712 256 1002',
    activeResponses: 1,
    inCharge: 'ACP Meera Khobragade',
    status: 'ACTIVE',
  },
  {
    id: 'PP-03',
    name: 'Police Post 3 (Zone C Crowd Control)',
    location: 'Zone C Laxmi Nagar Road',
    coords: [21.12600, 79.06680],
    officersCount: 22,
    vehicleUnits: 4,
    contact: '+91 712 256 1003',
    activeResponses: 4,
    inCharge: 'PI Rajesh Thool',
    status: 'ACTIVE',
  },
];

export const INITIAL_VOLUNTEERS: Volunteer[] = [
  {
    id: 'V-102',
    name: 'Aakash Dahat',
    phone: '+91 98221 11001',
    coords: [21.12790, 79.06710],
    status: 'AVAILABLE',
    zone: 'Zone B',
    skills: ['Child Escort', 'First Aid', 'Marathi/Hindi'],
    batteryPct: 92,
    lastActive: 'Just now',
    assignedDistanceMeters: 250,
  },
  {
    id: 'V-108',
    name: 'Bhavna Ramteke',
    phone: '+91 98221 11002',
    coords: [21.12640, 79.06680],
    status: 'BUSY',
    zone: 'Zone C',
    skills: ['Crowd Guidance', 'De-escalation'],
    batteryPct: 84,
    lastActive: '3m ago',
    assignedDistanceMeters: 180,
  },
  {
    id: 'V-117',
    name: 'Chetan Zade',
    phone: '+91 98221 11003',
    coords: [21.12840, 79.06750],
    status: 'AVAILABLE',
    zone: 'Zone B',
    skills: ['First Aid', 'Megaphone Lead'],
    batteryPct: 78,
    lastActive: 'Just now',
    assignedDistanceMeters: 430,
  },
  {
    id: 'V-125',
    name: 'Deepali Gajbhiye',
    phone: '+91 98221 11004',
    coords: [21.12920, 79.06730],
    status: 'AVAILABLE',
    zone: 'Zone A',
    skills: ['Medical Assist', 'CPR Certified'],
    batteryPct: 88,
    lastActive: '1m ago',
    assignedDistanceMeters: 520,
  },
  {
    id: 'V-130',
    name: 'Eknath Meshram',
    phone: '+91 98221 11005',
    coords: [21.12750, 79.06480],
    status: 'AVAILABLE',
    zone: 'Zone D',
    skills: ['Patrol', 'Guidance'],
    batteryPct: 95,
    lastActive: '2m ago',
    assignedDistanceMeters: 610,
  },
];

export const INITIAL_CCTV: CCTVCamera[] = [
  {
    id: 'CCTV-12',
    name: 'CCTV-12 (Zone B - Main Pathway Dome Approach)',
    zone: 'Zone B',
    coords: [21.12785, 79.06720],
    status: 'ONLINE',
    personCount: 420,
    density: 'NORMAL',
    streamType: 'ANALYTICS',
    recentDetections: [
      { timestamp: '10:50 AM', label: 'Match INC-2048 (Aarohi, 7yo)', confidence: 87 },
      { timestamp: '10:48 AM', label: 'Person Flow 48/min', confidence: 96 },
    ],
  },
  {
    id: 'CCTV-04',
    name: 'CCTV-04 (Zone A - Food Court & Water Stand)',
    zone: 'Zone A',
    coords: [21.12870, 79.06820],
    status: 'ONLINE',
    personCount: 890,
    density: 'HIGH',
    streamType: 'RGB',
    recentDetections: [
      { timestamp: '10:45 AM', label: 'Orderly Food Distribution', confidence: 94 },
    ],
  },
  {
    id: 'CCTV-06',
    name: 'CCTV-06 (Zone C - Laxmi Nagar Choke Point)',
    zone: 'Zone C',
    coords: [21.12620, 79.06690],
    status: 'ONLINE',
    personCount: 2150,
    density: 'CRITICAL',
    streamType: 'THERMAL',
    recentDetections: [
      { timestamp: '10:46 AM', label: 'High Density Surge', confidence: 98 },
    ],
  },
  {
    id: 'CCTV-08',
    name: 'CCTV-08 (Zone D - West Backside Path)',
    zone: 'Zone D',
    coords: [21.12785, 79.06450],
    status: 'ONLINE',
    personCount: 310,
    density: 'NORMAL',
    streamType: 'RGB',
    recentDetections: [
      { timestamp: '10:40 AM', label: 'Perimeter Normal', confidence: 97 },
    ],
  },
];

export const INITIAL_CROWD_ZONES: CrowdZone[] = [
  {
    id: 'ZONE-A',
    name: 'Zone A - Food Court & North Concourse',
    coords: [21.12890, 79.06750],
    currentCount: 4800,
    maxSafeCapacity: 6500,
    densityLevel: 'MODERATE',
    riskColor: 'YELLOW',
    trend: 'STABLE',
  },
  {
    id: 'ZONE-B',
    name: 'Zone B - Main Pathway (Stupa Sanctum)',
    coords: [21.12785, 79.06690],
    currentCount: 8400,
    maxSafeCapacity: 10000,
    densityLevel: 'HIGH',
    riskColor: 'ORANGE',
    trend: 'INCREASING',
  },
  {
    id: 'ZONE-C',
    name: 'Zone C - South Exit & Parking Area',
    coords: [21.12620, 79.06690],
    currentCount: 7840,
    maxSafeCapacity: 5000,
    densityLevel: 'CRITICAL',
    riskColor: 'RED',
    trend: 'INCREASING',
  },
  {
    id: 'ZONE-D',
    name: 'Zone D - Backside Path & West Lawn',
    coords: [21.12785, 79.06450],
    currentCount: 2200,
    maxSafeCapacity: 6000,
    densityLevel: 'LOW',
    riskColor: 'GREEN',
    trend: 'STABLE',
  },
];

export const INITIAL_EXIT_GATES: ExitGate[] = [
  {
    id: 'EXIT-01',
    name: 'Exit 1 (North VIP Gate)',
    coords: [21.12930, 79.06690],
    capacity: 6000,
    currentCrowd: 1950,
    entryFlowPerMin: 45,
    exitFlowPerMin: 180,
    congestionPct: 32,
    riskLevel: 'NORMAL',
    recommendedAction: 'Optimal evacuation route available.',
  },
  {
    id: 'EXIT-02',
    name: 'Exit 2 (East Main Exit)',
    coords: [21.12785, 79.06910],
    capacity: 8000,
    currentCrowd: 5200,
    entryFlowPerMin: 180,
    exitFlowPerMin: 220,
    congestionPct: 65,
    riskLevel: 'ELEVATED',
    recommendedAction: 'Keep two lanes clear for outgoing surge.',
  },
  {
    id: 'EXIT-03',
    name: 'Exit 3 (Zone B/C South Exit)',
    coords: [21.12615, 79.06690],
    capacity: 5000,
    currentCrowd: 7840,
    entryFlowPerMin: 290,
    exitFlowPerMin: 140,
    congestionPct: 96,
    riskLevel: 'CRITICAL',
    recommendedAction: 'CRITICAL: Divert incoming pilgrims towards Exit 02 and Gate 4 immediately.',
  },
];

export const INITIAL_MISSING_PERSONS: MissingPerson[] = [
  {
    id: 'MP-2048',
    incidentId: 'INC-2048',
    name: 'Aarohi',
    age: 7,
    gender: 'FEMALE',
    category: 'CHILD',
    photoUrl: 'https://images.unsplash.com/photo-1543332164-6e82f355badc?w=400&q=80',
    clothingDescription: 'Blue shirt, ponytail, pink shoes',
    lastKnownLocation: 'Zone B - Main Pathway',
    coords: [21.12785, 79.06690],
    lastSeenTime: '10:30 AM',
    contactPerson: 'Suresh & Family (Parents)',
    contactNumber: '+91 98765 43210',
    status: 'SEARCHING',
    matchedCctv: [
      {
        cameraId: 'CCTV-12',
        cameraLocation: 'Zone B - Main Pathway Dome Approach',
        timestamp: '10:50 AM',
        confidence: 87,
        status: 'CONFIRMED',
      },
    ],
  },
  {
    id: 'MP-102',
    incidentId: 'INC-2035',
    name: 'Devidas Meshram',
    age: 74,
    gender: 'MALE',
    category: 'ELDERLY',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&q=80',
    clothingDescription: 'White Kurta Pajama, walking cane',
    lastKnownLocation: 'Zone A - Food Court',
    coords: [21.12870, 79.06820],
    lastSeenTime: '09:15 AM',
    contactPerson: 'Raju Meshram',
    contactNumber: '+91 97654 32109',
    status: 'LOCATED',
    matchedCctv: [],
  },
];

export const INITIAL_SIGHTINGS: Sighting[] = [
  {
    id: 'SGT-201',
    incidentId: 'INC-2048',
    missingPersonName: 'Aarohi',
    reporterName: 'Pravin Godghate',
    reporterType: 'CITIZEN',
    location: 'Near Ice Cream kiosk behind Zone B',
    coords: [21.12790, 79.06730],
    timestamp: '10:44 AM',
    description: 'Saw young girl in blue shirt with ponytail looking for family near pathway.',
    photoUrl: 'https://images.unsplash.com/photo-1543332164-6e82f355badc?w=400&q=80',
    verificationStatus: 'VERIFIED',
    aiConfidence: 'HIGH',
    aiSimilarityScore: 87,
    consistencyCheck: {
      locationConsistent: true,
      timeConsistent: true,
      duplicateSuspected: false,
      notes: 'No duplicate reports. Evidence consistent (photo + description). CCTV-12 match available.',
    },
    verifiedBy: 'Desk-3 Operator',
    verifiedAt: '10:46 AM',
  },
  {
    id: 'SGT-202',
    incidentId: 'INC-2048',
    missingPersonName: 'Aarohi',
    reporterName: 'CCTV-12 Vision AI',
    reporterType: 'CCTV_AI',
    location: 'Zone B Dome Pathway Approach',
    coords: [21.12785, 79.06720],
    timestamp: '10:50 AM',
    description: 'Camera frame match: blue garment histogram and height alignment 87% match.',
    verificationStatus: 'VERIFIED',
    aiConfidence: 'HIGH',
    aiSimilarityScore: 87,
    consistencyCheck: {
      locationConsistent: true,
      timeConsistent: true,
      duplicateSuspected: false,
      notes: 'Biometric and clothing vector confirmed.',
    },
    verifiedBy: 'Control Room Officer',
    verifiedAt: '10:51 AM',
  },
];

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: 'INC-2048',
    type: 'MISSING_PERSON',
    title: 'Missing Child (Aarohi, 7yo)',
    reporter: {
      name: 'Family with Reporter',
      phone: '+91 98765 43210',
      role: 'CITIZEN',
    },
    location: 'Zone B - Main Pathway',
    coords: [21.12785, 79.06690],
    timestamp: '10:42 AM, 24 Sep 2025',
    description: 'Child wearing blue shirt, last seen near Main Pathway. Family is with the reporter.',
    evidence: {
      photoUrls: ['https://images.unsplash.com/photo-1543332164-6e82f355badc?w=400&q=80'],
    },
    severity: 'HIGH',
    verificationStatus: 'VERIFIED',
    status: 'RESPONDING',
    assignedDepartment: 'Volunteer Response & Police Post Zone B',
    assignedResponder: {
      id: 'V-102',
      name: 'Volunteer V-102 (Aakash Dahat)',
      type: 'VOLUNTEER',
      phone: '+91 98221 11001',
      assignedAt: '10:54 AM',
      distanceMeters: 250,
    },
    nearbyCctvIds: ['CCTV-12'],
    nearbyHelpDeskId: 'Desk-3',
    tags: ['Aarohi', 'Blue Shirt', 'Ponytail', 'Zone B'],
    timeline: [
      {
        id: 'TL-1',
        timestamp: '10:42 AM',
        title: 'Report received from citizen',
        description: 'Incident registered via Mobile SECUREMESH app at Zone B.',
        actor: 'Citizen Reporter',
        type: 'STATUS_CHANGE',
      },
      {
        id: 'TL-2',
        timestamp: '10:46 AM',
        title: 'AI verification completed (87%)',
        description: 'Evidence consistent, location & time correlation verified.',
        actor: 'AI Verification Engine',
        type: 'VERIFICATION',
      },
      {
        id: 'TL-3',
        timestamp: '10:50 AM',
        title: 'Related CCTV sighting found',
        description: 'CCTV-12 detected match on Main Pathway.',
        actor: 'CCTV-12 Analytics',
        type: 'ALERT',
      },
      {
        id: 'TL-4',
        timestamp: '10:54 AM',
        title: 'Volunteer V-102 assigned',
        description: 'Proximity dispatch engaged (250m away).',
        actor: 'Control Room Dispatcher',
        type: 'ASSIGNMENT',
      },
      {
        id: 'TL-5',
        timestamp: '11:10 AM',
        title: 'Child located',
        description: 'Child safely escorted to Desk-3 and reunited with parents.',
        actor: 'Volunteer V-102',
        type: 'STATUS_CHANGE',
      },
    ],
  },
  {
    id: 'INC-2035',
    type: 'THEFT',
    title: 'Chain Snatching near Zone A Food Court',
    reporter: {
      name: 'Sunita Dongre',
      phone: '+91 94228 11220',
      role: 'CITIZEN',
    },
    location: 'Zone A - Food Court',
    coords: [21.12870, 79.06820],
    timestamp: '09:15 AM, 24 Sep 2025',
    description: 'Gold chain snatched in crowded food distribution aisle. Suspect fled toward Exit 1.',
    severity: 'HIGH',
    verificationStatus: 'VERIFIED',
    status: 'RESPONDING',
    assignedDepartment: 'Nagpur Police Flying Squad',
    assignedResponder: {
      id: 'PP-02',
      name: 'Police Post 2 Unit',
      type: 'POLICE',
      phone: '+91 712 256 1002',
      assignedAt: '09:20 AM',
      distanceMeters: 120,
    },
    nearbyCctvIds: ['CCTV-04'],
    nearbyHelpDeskId: 'HD-02',
    tags: ['Chain Snatching', 'Zone A', 'Police Alert'],
    timeline: [],
  },
  {
    id: 'INC-2022',
    type: 'SUSPICIOUS_ACTIVITY',
    title: 'Suspicious Activity near Zone C Parking',
    reporter: {
      name: 'Volunteer V-108',
      phone: '+91 98221 11002',
      role: 'VOLUNTEER',
    },
    location: 'Zone C - Parking Area',
    coords: [21.12620, 79.06690],
    timestamp: '08:47 AM, 24 Sep 2025',
    description: 'Unattended bag noticed near motorcycle parking stand for over 30 minutes.',
    severity: 'MEDIUM',
    verificationStatus: 'VERIFIED',
    status: 'RESOLVED',
    assignedDepartment: 'Police Post 3 Quick Response Team',
    nearbyCctvIds: ['CCTV-06'],
    nearbyHelpDeskId: 'HD-04',
    tags: ['Unattended Object', 'Zone C'],
    timeline: [],
  },
  {
    id: 'INC-2018',
    type: 'CROWD_SURGE',
    title: 'Crowd Density High near Exit 3',
    reporter: {
      name: 'AI Sensor System',
      phone: 'SYSTEM',
      role: 'CONTROL_ROOM',
    },
    location: 'Zone C - Near Exit 3',
    coords: [21.12615, 79.06690],
    timestamp: '10:15 AM, 24 Sep 2025',
    description: 'Pedestrian bottleneck crossing 96% capacity limit. Immediate diversion recommended.',
    severity: 'CRITICAL',
    verificationStatus: 'VERIFIED',
    status: 'RESPONDING',
    assignedDepartment: 'Crowd Management Division',
    nearbyCctvIds: ['CCTV-06'],
    nearbyHelpDeskId: 'HD-04',
    tags: ['Crowd Bottleneck', 'Zone C', 'Exit 3'],
    timeline: [],
  },
  {
    id: 'INC-2015',
    type: 'SOS',
    title: 'SOS Emergency Request in Zone B',
    reporter: {
      name: 'Kavita Meshram',
      phone: '+91 98765 43210',
      role: 'CITIZEN',
    },
    location: 'Zone B - Near Main Pathway',
    coords: [21.12785, 79.06690],
    timestamp: '10:40 AM, 24 Sep 2025',
    description: 'Elderly family member feeling faint and dizzy in crowd. Stretcher requested.',
    severity: 'CRITICAL',
    verificationStatus: 'VERIFIED',
    status: 'RESPONDING',
    assignedDepartment: 'Emergency Medical Service',
    assignedResponder: {
      id: 'V-102',
      name: 'Volunteer V-102 (First Aid)',
      type: 'VOLUNTEER',
      phone: '+91 98221 11001',
      assignedAt: '10:41 AM',
      distanceMeters: 250,
    },
    nearbyCctvIds: ['CCTV-12'],
    nearbyHelpDeskId: 'Desk-3',
    tags: ['SOS', 'Medical', 'Zone B'],
    timeline: [],
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'NOTIF-01',
    type: 'CRITICAL',
    title: 'SOS - Zone B',
    message: 'Medical SOS beacon triggered near Main Pathway (2 min ago)',
    timestamp: '2 min ago',
    read: false,
    incidentId: 'INC-2015',
    actionLink: '/sos',
  },
  {
    id: 'NOTIF-02',
    type: 'WARNING',
    title: 'Crowd density high - Zone C',
    message: 'Exit 3 corridor capacity reached 96% threshold (5 min ago)',
    timestamp: '5 min ago',
    read: false,
    incidentId: 'INC-2018',
    actionLink: '/crowd',
  },
  {
    id: 'NOTIF-03',
    type: 'WARNING',
    title: 'Missing child - Zone A',
    message: 'Potential sighting match reported near Food Court (8 min ago)',
    timestamp: '8 min ago',
    read: false,
    incidentId: 'INC-2048',
    actionLink: '/sighting',
  },
  {
    id: 'NOTIF-04',
    type: 'INFO',
    title: 'Volunteer assigned - INC-2048',
    message: 'Volunteer V-102 assigned to Aarohi missing case (12 min ago)',
    timestamp: '12 min ago',
    read: true,
    incidentId: 'INC-2048',
    actionLink: '/incidents/INC-2048',
  },
  {
    id: 'NOTIF-05',
    type: 'WARNING',
    title: 'Threat report - Zone B',
    message: 'Suspicious activity reported near Exit 3 (18 min ago)',
    timestamp: '18 min ago',
    read: true,
    incidentId: 'INC-2022',
    actionLink: '/security-report',
  },
];

export const INITIAL_VEHICLE_TRIPS: VehicleTrip[] = [
  {
    id: 'TRIP-2026-809',
    vehicleNumber: 'MH-31-AZ-4921',
    vehicleType: 'SHARED_AUTO',
    driverName: 'Santosh Pandhare',
    driverPhone: '+91 98229 33441',
    passengerName: 'Komal Waghmare & 2 others',
    passengerPhone: '+91 97650 11228',
    passengerCount: 3,
    startPoint: 'Deekshabhoomi Transit Stand (Zone C)',
    destination: 'Sitabuldi Metro Station',
    plannedRoute: [
      [21.12550, 79.06780],
      [21.12900, 79.07100],
      [21.13500, 79.07700],
      [21.14300, 79.08200],
    ],
    currentPosition: [21.12050, 79.05500],
    routeHistory: [
      [21.12550, 79.06780],
      [21.12400, 79.06400],
      [21.12200, 79.05900],
      [21.12050, 79.05500],
    ],
    isDeviated: true,
    deviationDistanceMeters: 1450,
    status: 'DEVIATED_ALERT',
    startedAt: '10:30 AM',
    estimatedArrival: '10:48 AM',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'LOG-01',
    timestamp: '10:54 AM',
    actor: 'Control Room Dispatcher',
    role: 'CONTROL_ROOM',
    action: 'DISPATCH_VOLUNTEER',
    targetId: 'INC-2048',
    details: 'Dispatched Volunteer V-102 to verify CCTV-12 sighting.',
  },
  {
    id: 'LOG-02',
    timestamp: '10:50 AM',
    actor: 'CCTV-12 Vision Engine',
    role: 'ADMIN',
    action: 'AI_FACE_MATCH',
    targetId: 'INC-2048',
    details: 'Flagged 87% match on Main Pathway for Aarohi (7yo).',
  },
  {
    id: 'LOG-03',
    timestamp: '10:46 AM',
    actor: 'Desk-3 Operator',
    role: 'HELP_DESK',
    action: 'VERIFY_INCIDENT',
    targetId: 'INC-2048',
    details: 'Evidence verified and confidence scored at 87%.',
  },
];
